# NPM suspended me due I just add a new 2FA key for new machine. So I need to use this way instead.
# still not work. "Your account has been temporarily suspended due to a recent security-sensitive action."
# use "npm install DPSoftware-Technologies/node-red-dashboard-2-ui-lcd#main" instead
name: Publish Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
